RDKB-20483 : Upgrade lighttpd version to 1.4.45
Reason for change: Upgrade lighttpd version from 1.4.41 to 1.4.45. This is required for Morty migration of all RDK-B devices. This is cherry-picks from master branch of open embedded-core
Test Procedure: Build and run the image
Risks: none

lighttpd: update to 1.4.42

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 0ca7196bafa7d01afec4ca1e8c86c3a6f81bbf0b)

lighttpd: upgrade to 1.4.43

lighttpd no longer builds modules for which dependencies are not present,
so some previously available modules are no more.

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 1008d711b57d82313e53f767fd6fae93e10418ea)

lighttpd: Add many packageconfig options

Respect largefile and xattr distro features.

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 38eb51d4739cbac292abaef9d2888b6a54d32ad6)

lighttpd: access and accesslog are optional modules

Move them from RDEPENDS to RRECOMMENDS.

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit ef446586e4a44f13945241b501dc922c38beae58)

lighttpd: upgrade to 1.4.35

Signed-off-by: Valentin Popa <valentin.popa@intel.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
(cherry picked from commit cdbcadee68a47e985d25ba39359f3a3fa0049a8a)

lighthttp: Use pkg-config for pcre dependency

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d2457880e7bb08b9c2f8d60e70b1d59ed84e9da9)

lighttpd: install config file without execute permissions

Signed-off-by: Dan McGregor <dan.mcgregor@usask.ca>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit de8d70ccd846167df31037b7a89f7d13f6731cf6)

lighttpd: Use PACKAGECONFIG to enable openssl

Enabled openssl defalutly to use https, just like ubuntu do.

Signed-off-by: Qian Lei <qianl.fnst@cn.fujitsu.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 549c9cb6a7b0e989ffcefed8219eedaa6f13c6c8)

lighttpd: Fix mod_cgi to avoid it buffers data without bound.

If there is a CGI that provides a continuous stream of data,
If lighttpd client reads slower then the CGI is pushing the data,
then lighttpd's buffers will grow until the (embedded) machine OOMs.

Ref: http://redmine.lighttpd.net/issues/1264

Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 6d098587415be098913a3b551b0b7ee8c0270274)

lighttpd: 1.4.35 -> 1.4.36

Upgrade lighttpd from 1.4.35 to 1.4.36.

* Remove PR
* Update context of 0001-mod_cgi-buffers-data-without-bound.patch

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 082e54077a88a6104226bc7a2068ea6c10ea1f99)

lighttpd: update to 1.4.38

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
(cherry picked from commit cbe878b646ca728e97204a0eff6f1d8ccb16b523)

lighttpd: fix /usr/lib/mod_cgi.so: undefined symbol: chunkqueue_written

lighttpd fails to load when mod_cgi is enabled at run time, with the
message "dlopen() failed for: /usr/lib/mod_cgi.so /usr/lib/mod_cgi.so:
undefined symbol: chunkqueue_written".

This is caused by a patch intended to prevent memory exhaustion by
naively streaming CGIs, aimed at upstream issue
http://redmine.lighttpd.net/issues/1264 . The patch uses internal API
functions from older versions of lighttpd which don't exist in this
version.  Remove the patch, pending a better fix.

[ YOCTO #9289 ]

Signed-off-by: Nick Leverton <nick@leverton.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 880a346bf1bc4aa6c8569c6319c141433e13e1dd)

lighttpd: update to 1.4.41

Rebase pkgconfig.patch

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 45fac4161cb230bc03c6c08d21cc768e52700f02)

lighttpd: control ipv6 support based on DISTRO_FEATURES

Add PACKAGECONFIG for ipv6 and control it based
on DISTRO_FEATURES.

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d7b2afd41d650e30a4a1fc453cae3ab060a7da57)

lighttpd: fix EXTRA_OECONF

* --without-memcache was renamed to --without-memcached in:
  https://redmine.lighttpd.net/projects/lighttpd/repository/revisions/f3b577ddee36b9555331dfbcddb6a200df2ba438
* causing:
  ERROR: lighttpd-1.4.41-r0 do_configure: QA Issue: lighttpd: configure was passed unrecognised options: --without-memcache [unknown-configure-option]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit d53b220205259705649cb7741a21cb267519d565)

lighttpd: update to 1.4.42

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 0ca7196bafa7d01afec4ca1e8c86c3a6f81bbf0b)

lighttpd: upgrade to 1.4.43

lighttpd no longer builds modules for which dependencies are not present,
so some previously available modules are no more.

Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 1008d711b57d82313e53f767fd6fae93e10418ea)

lighttpd: Add many packageconfig options

Respect largefile and xattr distro features.

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 38eb51d4739cbac292abaef9d2888b6a54d32ad6)

lighttpd: access and accesslog are optional modules

Move them from RDEPENDS to RRECOMMENDS.

Signed-off-by: Andreas Oberritter <obi@opendreambox.org>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit ef446586e4a44f13945241b501dc922c38beae58)

lighttpd: Upgrade 1.4.43 -> 1.4.45

Signed-off-by: Andrej Valek <andrej.valek@siemens.com>
Signed-off-by: Pascal Bach <pascal.bach@siemens.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 94fc70a60a26c1bc402e0e410ab1992d3d9effb4)

(cherry picked from commit 456a8b7dfd038b1740472767e505b2dbf12d9c53)

lighttpd: Upgrade 1.4.43 -> 1.4.45

Signed-off-by: Andrej Valek <andrej.valek@siemens.com>
Signed-off-by: Pascal Bach <pascal.bach@siemens.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
(cherry picked from commit 94fc70a60a26c1bc402e0e410ab1992d3d9effb4)

Change-Id: I7fc4079bd1119153ef9342da5644ef05ab97367a